### ISSUE TITLE
Crash with sodium 0.4.0-alpha5+build.848

### ISSUE THREAD

**Issue by Titaniumtown** [FlashyReese/sodium-extra-fabric#123]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.1

### Sodium Extra version.

0.3.7

### Sodium version.

0.4.0-alpha5+build.848

### What happened?

Crashes when joining a server, this may be due to: https://github.com/CaffeineMC/sodium-fabric/commit/c1f71f72054f2d4826b3236c8bf8c9aa41459454 would be my best guess.

### Relevant logs

https://paste.gg/p/anonymous/6c6ff937239e4709ac074cbe3f518a2a

**Comment by wavgado** [comment]
Me Too

**Comment by nixls** [comment]
This happens because `BiomeColorBlender` class has been renamed to `ColorBlender` in the commit mentioned above https://github.com/CaffeineMC/sodium-fabric/commit/c1f71f72054f2d4826b3236c8bf8c9aa41459454

I was able to fix it by changing two lines in `src/main/java/me/flashyreese/mods/sodiumextra/mixin/sodium/MixinBlockRenderer.java`:
https://github.com/FlashyReese/sodium-extra-fabric/blob/9b7701c7a788d4bc3e5a72f43ff62ba897769cdd/src/main/java/me/flashyreese/mods/sodiumextra/mixin/sodium/MixinBlockRenderer.java#L5 change class import from `BiomeColorBlender` to `ColorBlender`
https://github.com/FlashyReese/sodium-extra-fabric/blob/9b7701c7a788d4bc3e5a72f43ff62ba897769cdd/src/main/java/me/flashyreese/mods/sodiumextra/mixin/sodium/MixinBlockRenderer.java#L26 change parameter type from `BiomeColorBlender` to `ColorBlender`

I built this mod against the latest commit version of Sodium 1.18.x/dev and it doesn't crash anymore.

**Comment by offbeat-stuff** [comment]
I also have this problem and when I applied your fix I showed error in SodiumOptionsMenu.java(maybe) and also in game in pojavlauncher I cannot open options menu while sodium extra is installed.
(notenoughcrashes say its because of sodium,sodium-extras)

Can you share your fix?

**Comment by FlashyReese** [comment]
Now resolved with https://github.com/FlashyReese/sodium-extra-fabric/commit/dd2c9d136a2ff293de3a6bc14a9dcc7bb15f2092
