### ISSUE TITLE
[Feature Request] Make "Reduce Resolution on macOS" available on Linux.

### ISSUE THREAD

**Issue by moesnow** [FlashyReese/sodium-extra-fabric#201]
I'm using Linux Mint 20.3. 
My physical resolution is 1920\*1080, and scaled resolution is 1536\*864 with hidpi 2x. 
But the resolution in minecraft is 3072\*1728 when fullscreen.
I have low fps and can't open "Reduce Resolution on macOS" option because it can't be selected.

Linux also need this option!

**Comment by FlashyReese** [comment]
The `Reduce Resolution on macOS` only works on macOS because it disables a GLFW window hint called `GLFW_COCOA_RETINA_FRAMEBUFFER`, and by looking at the name of that window hint as you might guess means it's for retina displays on macOS.

I believe you are looking for a mod like [ResolutionControl (fork for 1.18)](https://github.com/trisk/Resolution-Control) or [ResolutionControl+](https://www.curseforge.com/minecraft/mc-mods/resolutioncontrol) which downscales the actual resolution.
