### ISSUE TITLE
I'm confused

### ISSUE THREAD

**Issue by Endninja137** [FlashyReese/sodium-extra-fabric#271]
The Modrinth page is very vague, and on Curseforge, I can't tell if it adds back what sodium disables or if it disables the vanilla stuff that sodium doesn't change.

**Comment by FlashyReese** [comment]
Sodium is purely a rendering optimization mod. It doesn't provide features like animations, particles, etcetera to be toggled like OptiFine. This mod is meant to complement the missing features that Sodium will never be adding since disabling animations/particles and etcetera has minimal impact on performance compared to optimizing particle rendering and such.

**Comment by FlashyReese** [comment]
I do need to update both pages since they are a bit outdated, I just haven't gotten around to it yet.

**Comment by FlashyReese** [comment]
Both Modrinth and CurseForges pages have been updated.
