### ISSUE TITLE
Static FOV breaks any zoom mod.

### ISSUE THREAD

**Issue by Kichura** [FlashyReese/sodium-extra-fabric#28]
When the static FOV is set to off, Beginning to zoom in after that will cause the FOV to no longer respect the specific mod's FOV and instead just hides the view model from screen along with activating slowed mouse when held.

1: Have OK Zoomer, Sodium and Sodium Extras mods installed,
2: Set the "Static FOV" via Extras to off,
3: Exit the settings and activate the zoom,
4: It should break.

Without static FOV:
![zoom](https://user-images.githubusercontent.com/68134602/118251841-606a0b80-b4a8-11eb-8f12-a965e1aa931a.png)

With static FOV:
![broken](https://user-images.githubusercontent.com/68134602/118251904-72e44500-b4a8-11eb-8a30-17d68a1c25e3.png)

**Comment by K0-RR** [comment]
Not all zoom mods are affected - Wi Zoom works for me. I can't check OK Zoomer as it crashes for me.

**Comment by notsatvrn** [comment]
Confirmed broken with OK Zoomer.

**Comment by CodeF53** [comment]
Confirmed broken with tweakaroo zoom.

**Comment by CodeF53** [comment]
confirmed broken with spyglass.

https://youtu.be/j9_3quSJ3LI

**Comment by EnnuiL** [comment]
Hello, due to people sending issues about static FOV breaking Ok Zoomer, I almost ended making a fix myself, but then, I just realized something: there is no need for a static FOV option, because since 1.16.2, Vanilla already provides the "FOV Effects" option under Accessibility Options, which makes the FOV static if set at 0% (and is compatible with spyglasses and zoom mods, well, at least Ok Zoomer)

So, consider either removing the option, but have it still appear in the settings as an non-selectable option explaining via tooltips that Vanilla already provides an equivalent option under the aforementioned section; or simply mixin in a way that changes the internal vanilla option instead of the current solution, which is definitely not mod-friendly

**Comment by FlashyReese** [comment]
> Hello, due to people sending issues about static FOV breaking Ok Zoomer, I almost ended making a fix myself, but then, I just realized something: there is no need for a static FOV option, because since 1.16.2, Vanilla already provides the "FOV Effects" option under Accessibility Options, which makes the FOV static if set at 0% (and is compatible with spyglasses and zoom mods, well, at least Ok Zoomer)
> 
> So, consider either removing the option, but have it still appear in the settings as an non-selectable option explaining via tooltips that Vanilla already provides an equivalent option under the aforementioned section; or simply mixin in a way that changes the internal vanilla option instead of the current solution, which is definitely not mod-friendly

Sorry for the burden that this issue has cause.
 
I would prefer removing it completely instead of it taking up space on the user interface, but to avoid confusion and new issues being opened; I will most likely just have it appear as a non-selectable option with updated tooltips.
