### ISSUE TITLE
FPS Counter

### ISSUE THREAD

**Issue by Novampr** [FlashyReese/sodium-extra-fabric#294]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.2

### Sodium Extra version.

Latest

### Sodium version.

Latest

### What happened?

FPS Counter does not disappear when using panoramica, Mod dev says the FPS counter is not implemented properly

### Relevant log.

N/A

### Additional information.

Not Panoramica’s fault

**Comment by FlashyReese** [comment]
Alright, I've used Fabric API's HUD rendering callback to try to address this issue but it appears Panoramica doesn't simulate F1 properly. So I don't think Sodium Extra is entirely at fault here.

Using F1
![image](https://user-images.githubusercontent.com/30311066/208695681-4e7d2e7b-ad0c-4fe1-af74-10a35214d8d9.png)

When using Panoramica's R
![image](https://user-images.githubusercontent.com/30311066/208695402-319d52ba-17f7-4c07-871a-2dd8f6a4c48c.png)

Pause menu/other menus (Intended behavior, allows to user to see if FPS counter is displayed)
![image](https://user-images.githubusercontent.com/30311066/208697220-5e26860f-6e76-49e9-966c-0908e2c6d406.png)

Edit: I believe Panoramica is simulating the pause menu and F1 at the same time, but since the FPS counter is intended to be displayed in pause menus/options menus. I won't be changing this behavior, so you just need to disable the FPS counter manually.
