### ISSUE TITLE
Multi dimensional setting

### ISSUE THREAD

**Issue by 54712gamer123** [FlashyReese/sodium-extra-fabric#317]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my crash.

### Minecraft version.

1.18.2

### Sodium Extra version.

0.4.18

### Sodium version.

0.4.1

### What happened?

I enabled the multi dimensional setting where the fog stuff is and my game crashed. I thought nothing of it but whenever I relaunch my game and open my settings my Minecraft crashes.

### Relevant logs

The game crashed whilst mouseclicked event handler
Error: java.lang.RuntimeException: Mixin transformation of me.flashyreese.mods.sodiumextra.mixin.fog.DimensionOptionsAccessor failed

**Comment by FlashyReese** [comment]
> I enabled the multi dimensional setting where the fog stuff is and my game crashed. I thought nothing of it but whenever I relaunch my game and open my settings my Minecraft crashes.

You need to delete Sodium Extra's config located at `.minecraft/config/sodium-extra-options.json`

> The game crashed whilst mouseclicked event handler
Error: java.lang.RuntimeException: Mixin transformation of me.flashyreese.mods.sodiumextra.mixin.fog.DimensionOptionsAccessor failed

I can't replicate this issue with the information you have provided. It's likely that it failed to read the configuration and crashes because the configuration file is corrupted.
