### ISSUE TITLE
world dosent render properly if you mess with settings

### ISSUE THREAD

**Issue by overclockhero** [FlashyReese/sodium-extra-fabric#352]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.5.1 build 112

### Sodium version.

0.5.1

### What happened?

world dosent render properly if you mess with settings 
only 2 chunks render ok but farther chunks dosent render 
its mostly happens when you trying to mess with the settings 
specially fog setting and fov setting 
at first its runs ok but after tuching the settings its randomly bugs out and never gonna work again unlees you delete all settings filles in mincraft folder   

### Relevant log.

[latest.log](https://github.com/FlashyReese/sodium-extra-fabric/files/12339407/latest.log)

**Comment by MithicSpirit** [comment]
This issue is described in the [0.5.1 release notes](https://github.com/FlashyReese/sodium-extra-fabric/releases/tag/mc1.20.1-0.5.1). Re-enabling fog seems to fix it for me, even if you change the distance from the default (so I just set it well above my render distance and it looks like it's the same as if there was no fog).
