### ISSUE TITLE
Sodium Extra causes beacons to end on max build limit + FPS counter and coords in extras are rendered when F3 is open

### ISSUE THREAD

**Issue by ImGRUI** [FlashyReese/sodium-extra-fabric#378]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.1

### Sodium Extra version.

0.5.4

### Sodium version.

0.5.8

### What happened?

When Sodium Extra is installed, beacons end at the build limit (256 for nether and end, 320 for overworld), not at a much higher height than it should be. Issue also persists with single fog on. 2nd issue described in Additional Information.

### Relevant log.

With Sodium Extra:

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/91282421/5ec008aa-a7ef-48df-bc1d-3bd0f78103e5)

Log: https://mclo.gs/Uv6141T

With only sodium and FAPI:

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/91282421/33f30bad-008f-482a-82a2-2776836a0680)

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/91282421/73949d06-7e0d-4694-9f4e-cea37ab449e3)

Log: https://mclo.gs/jWQZQEG

### Additional information.

2nd issue with FPS counter and coords:

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/91282421/0e95571f-58ed-4451-8c27-fe9ea0e8091c)

**Comment by ItzSkyReed** [comment]
Perhaps it is worth adding an option to change the beam height of the beacon, starting from the world limit and increasing it as a percentage.

**Comment by ItzSkyReed** [comment]
I ran into this problem when I made a large wall of multicolored beacon, but my road is on y 240 in the nether, because of this, the building looks very bad

**Comment by mrjasonn** [comment]
Occurs on 1.20.4 as well

**Comment by ItzSkyReed** [comment]
Occurs on 1.20.5

**Comment by FlashyReese** [comment]
You can temporarily add `render.block.entity=false` at `.minecraft/config/sodium-extra.properties` to disable this. It also disables beacon beam, piston and enchanting table toggles. 

Caused by https://github.com/FlashyReese/sodium-extra-fabric/blob/cdb15d75cdca99813b17b4e64c47000940009f8b/src/main/java/me/flashyreese/mods/sodiumextra/mixin/render/block/entity/MixinBeaconBlockEntityRenderer.java#L36

**Comment by ItzSkyReed** [comment]
Thanks!

**Comment by dbrighthd** [comment]
> You can temporarily add `render.block.entity=false` at `.minecraft/config/sodium-extra.properties` to disable this. It also disables beacon beam, piston and enchanting table toggles.
> 
> Caused by
> 
> https://github.com/FlashyReese/sodium-extra-fabric/blob/cdb15d75cdca99813b17b4e64c47000940009f8b/src/main/java/me/flashyreese/mods/sodiumextra/mixin/render/block/entity/MixinBeaconBlockEntityRenderer.java#L36

I dont mean to necropost, but I tried adding that to my sodium-extra.properties and the issue is still there for me (I can't update my sodium extra because I am still on 1.20.1)
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/68525639/9f1b9c4d-4ed6-47ea-b26d-561e0763a8a5)

Is there something else I should do?

**Comment by dbrighthd** [comment]
Oh it seems putting mixin.render.block.entity=false fixed it (putting mixing. before it)
