### ISSUE TITLE
You require a version that doesn't exist.

### ISSUE THREAD

**Issue by MagmaSlime123** [FlashyReese/sodium-extra-fabric#386]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.19.4.

### Sodium Extra version.

0.4.18.

### Sodium version.

0.4.10.

### What happened?

Title. Fabric complains about a version of Sodium called 0.4.11, which does not exist.

### Relevant log.

None. Fabric brings up its dependency/error screen explaining this issue.

### Additional information.

N/A. Please remove this unusable version.

**Comment by FlashyReese** [comment]
[It does exist](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.19.4-0.4.11), it was removed and shouldn't be used due to several issues. I can't replicate your issue. You might have dependency overrides left over from another modpack. You can check if you have a file named `.minecraft/config/fabric_loader_dependencies.json` and delete it or modify it.

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/58ea0733-724b-4d4b-888a-39e30918744c)
