### ISSUE TITLE
Clouds do not use custom fog start multiplier

### ISSUE THREAD

**Issue by BlueStaggo** [FlashyReese/sodium-extra-fabric#392]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/FlashyReese/sodium-extra-fabric/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.20.4

### Sodium Extra version.

0.5.4

### Sodium version.

0.5.8

### What happened?

Adjusting the fog start multiplier does not affect the fog on clouds.

### Relevant log.

Irrelevant

### Additional information.

![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/71090710/8c1ce1fa-9070-403c-9f55-6299eea08709)

**Comment by FlashyReese** [comment]
I don't see the issue here, the fog is starting earlier as intended. The feature doesn't make the fog as dense.

**Comment by BlueStaggo** [comment]
The issue is with the clouds as they don't have the fog setting applied. The fog on clouds fade out over a shorter distance than the custom setting.

**Comment by FlashyReese** [comment]
I think the issue here stems from Sodium's cloud renderer
![image](https://github.com/FlashyReese/sodium-extra-fabric/assets/30311066/f8476de7-7354-4222-aa22-dfd80ac7dccf)

You can disable Sodium's cloud renderer by adding `mixin.features.render.world.clouds=false` to `.minecraft/config/sodium-mixins.properties`.

**Comment by BlueStaggo** [comment]
Works like a dream. Thanks! Would be nice if you added in a tooltip in-game to let people know about this.
