### ISSUE TITLE
Video Settings Menu Glitch

### ISSUE THREAD

**Issue by iSeekerTW** [FlashyReese/sodium-extra-fabric#48]
Unable to see the video settings menu in sodium extra. I'm running Minecraft on an M1 MacBook Pro using rosetta 2 :)
As you can see from the attachments, the descriptions of the settings are showing up, but the actual settings aren't 
<img width="1440" alt="截屏2021-07-12 下午9 01 03" src="https://user-images.githubusercontent.com/56954729/125291944-8864d680-e354-11eb-9b96-f527a2372d8d.png">

<img width="1440" alt="截屏2021-07-12 下午9 01 02" src="https://user-images.githubusercontent.com/56954729/125291938-8733a980-e354-11eb-9a97-4c2c075e8f14.png">

**Comment by FlashyReese** [comment]
This probably caused by the `glScissor` function, will need to investigate.

**Comment by jaded33** [comment]
Same here Apple MacBook M1 as well.

**Comment by Avakining** [comment]
This happens to me on an Intel MacBook Pro as well, so it's not necessarily from the Rosetta 2 emulation

**Comment by PeterTheSalmon** [comment]
Yes, can confirm it also occurs on my Intel MBP

**Comment by DioEgizio** [comment]
yeah also occours on iMac 27" 2017

**Comment by FlashyReese** [comment]
I've attempted a fix, since I don't have a Mac nor know anyone that does, I'll leave this build here for testing.
https://cdn.discordapp.com/attachments/812215092510195732/871977341809733652/sodium-extra-mc1.17.1-0.3.3-6222d320ef.jar

**Comment by Sputnik1947** [comment]
I am using an Intel MacBook Pro and used the test build you sent. I am still seeing this same issue show up with the test build.
I was able to find though that the issue seems to only occur when I put the game on my built-in display. Whenever I have it on my Asus monitor, the Video Settings Menu shows up completely normally. And even with the game already launched, I can switch between not showing the menu and showing it by moving the game window to my built-in screen or to my monitor, respectively.
For me, at least, the messed up menu is only occurring when I am using my built-in display. Here is an example of what it looks like on my built-in monitor.

<img width="924" alt="Screen Shot 2021-08-03 at 6 27 02 AM" src="https://user-images.githubusercontent.com/88380529/128008497-97e68232-dc7f-4adb-9192-b54e1b74aeac.png">

**Comment by FroggDogg** [comment]
Turns out its an issue with the resolution of the screen, if you airplay your Mac's screen to a different device with a different resolution the video settings shows up without the game having to be moved to a separate monitor. Basically it's something to do with the resolution the only way I've found to solve this is by airplay or another monitor.

**Comment by FlashyReese** [comment]
Yes, I have discovery that with some users on our Discord server but you can temporarily run [retiNO](https://www.curseforge.com/minecraft/mc-mods/retino) until a proper solution is integrated.

**Comment by PeterTheSalmon** [comment]
Yes, retiNO seems to be the best (and only) solution at the moment.

**Comment by FlashyReese** [comment]
I've opted to release the GUI changes as separate mod instead of including it. Additional I have added a feature with https://github.com/FlashyReese/sodium-extra-fabric/commit/9931a07ce3299f8c491463fc99c7befe7b4cef2e that should fix the issue
